[project]
name = "ptg-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pymongo>=4.13.0",
    "streamlit>=1.45.1",
]
