[theme]
primaryColor="#ff5c8d"  # Vibrant pink
backgroundColor="#1e1e2e"  # Deep charcoal
secondaryBackgroundColor="#2d2d3d"  # Slightly lighter charcoal
textColor="#e0e0e0"  # Off-white text
font="monospace"

[server]
headless = true
enableCORS = false

[general]
pageTitle = "Path to Glory App"
