[theme]
primaryColor="#d33682"
backgroundColor="#fdf6e3"
secondaryBackgroundColor="#eee8d5"
textColor="#586e75"
font="monospace"

[server]
headless = true
enableCORS = false

[general]
pageTitle = "Path to Glory App"
